### ISSUE TITLE
Support Ecto 2.2

### ISSUE THREAD

**Issue by shdblowers** [findmypast-oss/mssql_ecto#25]
There are changes coming in Ecto 2.2 which will require changes to our adapter.

See https://github.com/elixir-ecto/ecto/pull/2155 for details.

**Comment by shdblowers** [comment]
started work here: https://github.com/findmypast-oss/mssql_ecto/tree/ecto_2_2

**Comment by ndarilek** [comment]
Any updates on this? Just hit this one myself. Should I just downgrade Ecto, or is there more to it?

Thanks!

**Comment by shdblowers** [comment]
Ran into some snags and haven't revisited since September, current workaround is to indeed downgrade to Ecto 2.1

**Comment by nobaux** [comment]
Hope so we get 2.2 coz https://github.com/elixir-ecto/ecto/issues/1923

**Comment by josevalim** [comment]
If somebody is working on it and has any issue, please let me know, I will be glad to help in any way.

**Comment by shdblowers** [comment]
Thanks for your offer of help @josevalim, I will have another crack at doing the upgrade in the coming weekends, will let you know if I get stuck.

**Comment by shdblowers** [comment]
upgrade to ecto 2.2 complete, released as version 1.1
