### ISSUE TITLE
Can't open lib

### ISSUE THREAD

**Issue by cpursley** [findmypast-oss/mssql_ecto#35]
`[unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2'`

## Expected Behavior
This worked before. Expected to fire right up.

## Current Behavior
Example fails when running `docker-compose mix setup`

## Possible Solution
Not sure, I've fiddled a bunch with the Elixir Dockerfile (tried setting msodbcsql, mssql-tools and unixodbc-dev versions).

Perhaps this an issue with the official MSSQL Docker image? I was not able to get running on macOS either.

## Steps to Reproduce (for bugs)
```bash
$ docker-compose build
$ docker-compose up
```
In separate terminal:
```bash
$ docker-compose mix setup
```

## Context
Silently failed on me with any changes to mssql_ecto version or Docker.

## Your Environment
* MssqlEcto version: `1.0.0`
* Ecto version: `2.1.0`
* Elixir version: `1.6`
* Erlang version: `20`
* Microsoft SQL Server version: `microsoft/mssql-server-linux:latest`
* Operating System and version: `macOS High Sierra 10.13.3`
* Link to your project: https://github.com/cpursley/mssql_ecto_friends/issues/2

**Comment by shdblowers** [comment]
Microsoft have switched back to shipping version 17, maybe give that a go? Add this as docker compose environment variable
`- MSSQL_DVR={ODBC Driver 17 for SQL Server}`.
