### ISSUE TITLE
Associations do not work with non-standard primary keys

### ISSUE THREAD

**Issue by cpursley** [findmypast-oss/mssql_ecto#39]
When using non-standard primary keys in a legacy database schema, mssql_ecto associations are building out incompatible foreign keys.

An example primary key _source_ in the database is `UserID` while the ecto alias of that is `user_id`. Mssql creates a foreign key like `user_id_id`.

**Comment by cpursley** [comment]
`has_many` works, but it only returns one result.

**Comment by jbachhardie** [comment]
I'll try to take a look at this but I don't have much time at the moment so any help would be appreciated.

**Comment by cpursley** [comment]
Turns out the bug was in my head, not the code ;)

Closing.
